"""blood table

Revision ID: be3ebfe61ba4
Revises: 
Create Date: 2019-10-28 20:13:48.438232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3ebfe61ba4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_type', sa.String(3), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('suitablity', sa.Boolean(), nullable=False),
    sa.Column('use_by_date', sa.Date(), nullable=False),
    sa.Column('location_donated', sa.Text(), nullable=False),
    sa.Column('blood_donor_name', sa.Text(), nullable=False),
    sa.Column('blood_donor_email', sa.Text(), nullable=False),
    sa.CheckConstraint('volume > 0', name='check_volume'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('date_required', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blood_order',
    sa.Column('medical_id', sa.Integer(), nullable=False),
    sa.Column('blood_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('date_required', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['blood_id'], ['blood.id'], ),
    sa.ForeignKeyConstraint(['medical_id'], ['medical_facility.id'], ),
    sa.PrimaryKeyConstraint('medical_id', 'blood_id'),
    sa.UniqueConstraint('blood_id')
    )
    op.create_table('requested_blood',
    sa.Column('blood_type', sa.String(3), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('blood_request_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('volume > 0', name='check_requested_volume'),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_request.id'], ),
    sa.PrimaryKeyConstraint('blood_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requested_blood')
    op.drop_table('blood_order')
    op.drop_table('medical_facility')
    op.drop_table('blood_request')
    op.drop_table('blood')
    # ### end Alembic commands ###
